# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 6.0.3", ">= 6.0.3.7"
# Use mysql as the database for Active Record
gem "mysql2", ">= 0.4.4"
# Use Puma as the app server
gem "puma", "~> 4.1"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'mini_racer'

gem 'uglifier'
gem 'jquery-rails'
gem 'bootstrap', '~> 5.2.0'
gem 'sass-rails'
gem 'turbolinks'
gem 'autoprefixer-rails'

gem 'faker', '2.22.0'
gem 'will_paginate', '~> 3.3'
gem 'will_paginate-bootstrap-style'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# crypt password
gem "bcrypt"

# JWT
# gem "jwt"

# gem "line-bot-api"

# gem "google_drive"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem "pry-rails", platforms: %i[mri mingw x64_mingw]
  gem "pry-nav"
  gem "rspec-rails"
  # gem "factory_bot_rails"
  # gem "dotenv-rails"
end

group :development do
  # gem "rails-erd"
  gem "listen", "~> 3.2"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-performance"
  gem "rubocop-discourse"
  # for graphiql IDE
  gem "sprockets", "~> 3"
  # for graphiql IDE
  # gem "graphiql-rails"
  # gem "brakeman"
end

group :test do
  # gem "simplecov", require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "timecop", "~> 0.9.5"
